### ISSUE TITLE
Questions about the original data set

### ISSUE THREAD

**Issue by FangYuanXiong** [AICS-RLGroup/VirtualTaobao-Imp#1]
I want to build a simulator for my dataset.In the readme and the original paper, it is not clear what attributes the original user and item need to have and how to vectorize to get the corresponding dimension.Can you give a certain explanation about the original data?Thank you!

**Comment by RITCHIEHuang** [comment]
As the data is provided by the company a long time ago, we don't have them at the moment. From the view of building the virtual simulator, it cares more about the basic RL assumptions but not on the details of data items, we use `(s, a, s')` as an abstract concept `Transition`, which should be valid in your specific design to satisfy the RL requirements.

**Comment by RITCHIEHuang** [comment]
> I want to build a simulator for my dataset.In the readme and the original paper, it is not clear what attributes the original user and item need to have and how to vectorize to get the corresponding dimension.Can you give a certain explanation about the original data?Thank you!

As the data is provided by the company a long time ago, we don't have them at the moment. From the view of building the virtual simulator, it cares more about the basic RL assumptions but not on the details of data items, we use `(s, a, s')` as an abstract concept `Transition`, which should be valid in your specific design to satisfy the RL requirements.

**Comment by RITCHIEHuang** [comment]
> I want to build a simulator for my dataset.In the readme and the original paper, it is not clear what attributes the original user and item need to have and how to vectorize to get the corresponding dimension.Can you give a certain explanation about the original data?Thank you!

As the data was provided by the company years ago, we don't have them at the moment. From the view of building the virtual simulator, the algorithm  itself cares more about the basic RL assumptions but not the details of data items, we refer `(s, a, s')` as an abstract concept `Transition`, which should be valid in your specific design to satisfy the RL requirements.
